### ISSUE TITLE
Implement "Source and Destination Checks" flag for servers

### ISSUE THREAD

**Issue by timwsuqld** [oscarhermoso/terraform-provider-binarylane#46]
https://api.binarylane.com.au/reference/#tag/ServerActions/paths/~1v2~1servers~1%7Bserver_id%7D~1actions#ChangeSourceAndDestinationCheck/post

Being able to change `change_source_and_destination_check` is important for setting up a VPN/NAT server in a VPC. While the default is enabled, it prevents you using the server as a VPN/NAT endpoint. Currently need to manually change this in the UI.

Thanks

**Comment by oscarhermoso** [comment]
Hi @timwsuqld,

The `source_and_destination_check` will be available on the server resource with v0.8.3 of the provider, which is releasing right now.

Very cool to see that you are using the VPC features. If you have the free time & skills, I would love it if someone could contribute to the VPC example.

https://github.com/oscarhermoso/terraform-provider-binarylane/blob/main/examples/vpc/main.tf

**Comment by timwsuqld** [comment]
@oscarhermoso thanks for your work, and quick responses. You appear to be local to me too (the state in my username is work related).

I had a quick look at the example VPC config, that's what I used to setup my VPC, so I think it's pretty usable, especially now we have `source_and_destination_check`. I have pretty much your example (but reduced) working in production now. More static routes due to our environment, but other than that, your example is great.

Thanks
